#pragma once

#include <QDebug>
#include <easy/profiler.h>

#ifdef _DEBUG
#define QSFML_PROFILING
#endif

// Profiling
#ifdef QSFML_PROFILING
	
	#define QSFMLP_BLOCK(text, color) EASY_BLOCK(text, profiler::colors:: color)
	#define QSFMLP_END_BLOCK EASY_END_BLOCK
	#define QSFMLP_FUNCTION(color) EASY_FUNCTION(profiler::colors:: color)
#else
	#define QSFMLP_BLOCK(text, color)
	#define QSFMLP_END_BLOCK
	#define QSFMLP_FUNCTION(color)
#endif
#define CONCAT_SYMBOLS_IMPL(x, y) x##y
#define CONCAT_SYMBOLS(x, y) CONCAT_SYMBOLS_IMPL(x, y)

// Different color stages
#define QSFMLP_COLOR_STAGE_1 50
#define QSFMLP_COLOR_STAGE_2 100
#define QSFMLP_COLOR_STAGE_3 200
#define QSFMLP_COLOR_STAGE_4 300
#define QSFMLP_COLOR_STAGE_5 400
#define QSFMLP_COLOR_STAGE_6 500
#define QSFMLP_COLOR_STAGE_7 600
#define QSFMLP_COLOR_STAGE_8 700
#define QSFMLP_COLOR_STAGE_9 800
#define QSFMLP_COLOR_STAGE_10 900
#define QSFMLP_COLOR_STAGE_11 A100 
#define QSFMLP_COLOR_STAGE_12 A200 
#define QSFMLP_COLOR_STAGE_13 A400 
#define QSFMLP_COLOR_STAGE_14 A700 

// Colors for Canvas 
#define QSFMLP_CANVAS_COLORBASE Green
#define QSFMLP_CANVAS_COLOR_1  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_1 )
#define QSFMLP_CANVAS_COLOR_2  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_2 )
#define QSFMLP_CANVAS_COLOR_3  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_3 )
#define QSFMLP_CANVAS_COLOR_4  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_4 )
#define QSFMLP_CANVAS_COLOR_5  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_5 )
#define QSFMLP_CANVAS_COLOR_6  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_6 )
#define QSFMLP_CANVAS_COLOR_7  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_7 )
#define QSFMLP_CANVAS_COLOR_8  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_8 )
#define QSFMLP_CANVAS_COLOR_9  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_9 )
#define QSFMLP_CANVAS_COLOR_10 CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_10)
#define QSFMLP_CANVAS_COLOR_11 CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_11) 
#define QSFMLP_CANVAS_COLOR_12 CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_12) 
#define QSFMLP_CANVAS_COLOR_13 CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_13) 
#define QSFMLP_CANVAS_COLOR_14 CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_14) 

// Colors for CanvasContainer
#define QSFMLP_CANVASCONTAINER_COLORBASE LightGreen
#define QSFMLP_CANVASCONTAINER_COLOR_1  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_1 )
#define QSFMLP_CANVASCONTAINER_COLOR_2  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_2 )
#define QSFMLP_CANVASCONTAINER_COLOR_3  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_3 )
#define QSFMLP_CANVASCONTAINER_COLOR_4  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_4 )
#define QSFMLP_CANVASCONTAINER_COLOR_5  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_5 )
#define QSFMLP_CANVASCONTAINER_COLOR_6  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_6 )
#define QSFMLP_CANVASCONTAINER_COLOR_7  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_7 )
#define QSFMLP_CANVASCONTAINER_COLOR_8  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_8 )
#define QSFMLP_CANVASCONTAINER_COLOR_9  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_9 )
#define QSFMLP_CANVASCONTAINER_COLOR_10 CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_10)
#define QSFMLP_CANVASCONTAINER_COLOR_11 CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_11) 
#define QSFMLP_CANVASCONTAINER_COLOR_12 CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_12) 
#define QSFMLP_CANVASCONTAINER_COLOR_13 CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_13) 
#define QSFMLP_CANVASCONTAINER_COLOR_14 CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_14) 

// Colors for Threads
#define QSFMLP_THREAD_COLORBASE Blue
#define QSFMLP_THREAD_COLOR_1  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_1 )
#define QSFMLP_THREAD_COLOR_2  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_2 )
#define QSFMLP_THREAD_COLOR_3  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_3 )
#define QSFMLP_THREAD_COLOR_4  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_4 )
#define QSFMLP_THREAD_COLOR_5  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_5 )
#define QSFMLP_THREAD_COLOR_6  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_6 )
#define QSFMLP_THREAD_COLOR_7  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_7 )
#define QSFMLP_THREAD_COLOR_8  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_8 )
#define QSFMLP_THREAD_COLOR_9  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_9 )
#define QSFMLP_THREAD_COLOR_10 CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_10)
#define QSFMLP_THREAD_COLOR_11 CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_11) 
#define QSFMLP_THREAD_COLOR_12 CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_12) 
#define QSFMLP_THREAD_COLOR_13 CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_13) 
#define QSFMLP_THREAD_COLOR_14 CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_14) 

// Colors for ObjectGroup
#define QSFMLP_OBJECTGROUP_COLORBASE Yellow
#define QSFMLP_OBJECTGROUP_COLOR_1  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_1 )
#define QSFMLP_OBJECTGROUP_COLOR_2  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_2 )
#define QSFMLP_OBJECTGROUP_COLOR_3  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_3 )
#define QSFMLP_OBJECTGROUP_COLOR_4  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_4 )
#define QSFMLP_OBJECTGROUP_COLOR_5  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_5 )
#define QSFMLP_OBJECTGROUP_COLOR_6  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_6 )
#define QSFMLP_OBJECTGROUP_COLOR_7  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_7 )
#define QSFMLP_OBJECTGROUP_COLOR_8  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_8 )
#define QSFMLP_OBJECTGROUP_COLOR_9  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_9 )
#define QSFMLP_OBJECTGROUP_COLOR_10 CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_10)
#define QSFMLP_OBJECTGROUP_COLOR_11 CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_11) 
#define QSFMLP_OBJECTGROUP_COLOR_12 CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_12) 
#define QSFMLP_OBJECTGROUP_COLOR_13 CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_13) 
#define QSFMLP_OBJECTGROUP_COLOR_14 CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_14) 


// Colors for CanvasObject 
#define QSFMLP_OBJECT_COLORBASE Orange
#define QSFMLP_OBJECT_COLOR_1  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_1 )
#define QSFMLP_OBJECT_COLOR_2  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_2 )
#define QSFMLP_OBJECT_COLOR_3  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_3 )
#define QSFMLP_OBJECT_COLOR_4  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_4 )
#define QSFMLP_OBJECT_COLOR_5  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_5 )
#define QSFMLP_OBJECT_COLOR_6  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_6 )
#define QSFMLP_OBJECT_COLOR_7  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_7 )
#define QSFMLP_OBJECT_COLOR_8  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_8 )
#define QSFMLP_OBJECT_COLOR_9  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_9 )
#define QSFMLP_OBJECT_COLOR_10 CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_10)
#define QSFMLP_OBJECT_COLOR_11 CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_11) 
#define QSFMLP_OBJECT_COLOR_12 CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_12) 
#define QSFMLP_OBJECT_COLOR_13 CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_13) 
#define QSFMLP_OBJECT_COLOR_14 CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_14) 

// Colors for Physics stuff 
#define QSFMLP_PHYSICS_COLORBASE Cyan
#define QSFMLP_PHYSICS_COLOR_1  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_1 )
#define QSFMLP_PHYSICS_COLOR_2  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_2 )
#define QSFMLP_PHYSICS_COLOR_3  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_3 )
#define QSFMLP_PHYSICS_COLOR_4  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_4 )
#define QSFMLP_PHYSICS_COLOR_5  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_5 )
#define QSFMLP_PHYSICS_COLOR_6  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_6 )
#define QSFMLP_PHYSICS_COLOR_7  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_7 )
#define QSFMLP_PHYSICS_COLOR_8  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_8 )
#define QSFMLP_PHYSICS_COLOR_9  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_9 )
#define QSFMLP_PHYSICS_COLOR_10 CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_10)
#define QSFMLP_PHYSICS_COLOR_11 CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_11) 
#define QSFMLP_PHYSICS_COLOR_12 CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_12) 
#define QSFMLP_PHYSICS_COLOR_13 CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_13) 
#define QSFMLP_PHYSICS_COLOR_14 CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_14) 
