#pragma once

#include <QDebug>

#ifdef _DEBUG
//#define QSFML_PROFILING
#endif

// Profiling
#ifdef QSFML_PROFILING
	#include <easy/profiler.h>
	#include <easy/arbitrary_value.h> // EASY_VALUE, EASY_ARRAY are defined here

	#define QSFMLP_BLOCK_C(text, color) EASY_BLOCK(text, color)
	#define QSFMLP_NONSCOPED_BLOCK_C(text, color) EASY_NONSCOPED_BLOCK(text, color)
	#define QSFMLP_END_BLOCK EASY_END_BLOCK
	#define QSFMLP_FUNCTION_C(color) EASY_FUNCTION(color)
	#define QSFMLP_BLOCK(text, colorStage) QSFMLP_BLOCK_C(text,profiler::colors::  colorStage)
	#define QSFMLP_NONSCOPED_BLOCK(text, colorStage) QSFMLP_NONSCOPED_BLOCK_C(text,profiler::colors::  colorStage)
	#define QSFMLP_FUNCTION(colorStage) QSFMLP_FUNCTION_C(profiler::colors:: colorStage)
	#define QSFMLP_THREAD(name) EASY_THREAD(name)

	#define QSFMLP_VALUE(name, value) EASY_VALUE(name, value)
	#define QSFMLP_TEXT(name, value) EASY_TEXT(name, value)
#else
	#define QSFMLP_BLOCK_C(text, color) 
	#define QSFMLP_NONSCOPED_BLOCK_C(text, color) 
	#define QSFMLP_END_BLOCK
	#define QSFMLP_FUNCTION_C(color) 
	#define QSFMLP_BLOCK(text, colorStage) 
	#define QSFMLP_NONSCOPED_BLOCK(text, colorStage) 
	#define QSFMLP_FUNCTION(colorStage)
	#define QSFMLP_THREAD(name)

	#define QSFMLP_VALUE(name, value) 
	#define QSFMLP_TEXT(name, value)
#endif
#define CONCAT_SYMBOLS_IMPL(x, y) x##y
#define CONCAT_SYMBOLS(x, y) CONCAT_SYMBOLS_IMPL(x, y)

// Different color stages
#define QSFMLP_COLOR_STAGE_1 50
#define QSFMLP_COLOR_STAGE_2 100
#define QSFMLP_COLOR_STAGE_3 200
#define QSFMLP_COLOR_STAGE_4 300
#define QSFMLP_COLOR_STAGE_5 400
#define QSFMLP_COLOR_STAGE_6 500
#define QSFMLP_COLOR_STAGE_7 600
#define QSFMLP_COLOR_STAGE_8 700
#define QSFMLP_COLOR_STAGE_9 800
#define QSFMLP_COLOR_STAGE_10 900
#define QSFMLP_COLOR_STAGE_11 A100 
#define QSFMLP_COLOR_STAGE_12 A200 
#define QSFMLP_COLOR_STAGE_13 A400 
#define QSFMLP_COLOR_STAGE_14 A700 


// General
#define QSFMLP_GENERAL_COLORBASE Cyan
#define QSFMLP_GENERAL_BLOCK_C(text, color) QSFMLP_BLOCK_C(text, color)
#define QSFMLP_GENERAL_NONSCOPED_BLOCK_C(text, color) QSFMLP_NONSCOPED_BLOCK_C(text, color)
#define QSFMLP_GENERAL_END_BLOCK QSFMLP_END_BLOCK;
#define QSFMLP_GENERAL_FUNCTION_C(color) QSFMLP_FUNCTION_C(color)
#define QSFMLP_GENERAL_BLOCK(text, colorStage) QSFMLP_BLOCK(text, CONCAT_SYMBOLS(QSFMLP_GENERAL_COLORBASE, colorStage))
#define QSFMLP_GENERAL_NONSCOPED_BLOCK(text, colorStage) QSFMLP_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(QSFMLP_GENERAL_COLORBASE, colorStage))
#define QSFMLP_GENERAL_FUNCTION(colorStage) QSFMLP_FUNCTION(CONCAT_SYMBOLS(QSFMLP_GENERAL_COLORBASE, colorStage))
#define QSFMLP_GENERAL_VALUE(name, value) QSFMLP_VALUE(name, value)
#define QSFMLP_GENERAL_TEXT(name, value) QSFMLP_TEXT(name, value)

// Canvas
#define QSFMLP_CANVAS_COLORBASE Green
#define QSFMLP_CANVAS_BLOCK_C(text, color) QSFMLP_BLOCK_C(text, color)
#define QSFMLP_CANVAS_NONSCOPED_BLOCK_C(text, color) QSFMLP_NONSCOPED_BLOCK_C(text, color)
#define QSFMLP_CANVAS_END_BLOCK QSFMLP_END_BLOCK;
#define QSFMLP_CANVAS_FUNCTION_C(color) QSFMLP_FUNCTION_C(color)
#define QSFMLP_CANVAS_BLOCK(text, colorStage) QSFMLP_BLOCK(text, CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE, colorStage))
#define QSFMLP_CANVAS_NONSCOPED_BLOCK(text, colorStage) QSFMLP_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE, colorStage))
#define QSFMLP_CANVAS_FUNCTION(colorStage) QSFMLP_FUNCTION(CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE, colorStage))
#define QSFMLP_CANVAS_VALUE(name, value) QSFMLP_VALUE(name, value)
#define QSFMLP_CANVAS_TEXT(name, value) QSFMLP_TEXT(name, value)

// Objects
#define QSFMLP_OBJECT_COLORBASE Orange
#define QSFMLP_OBJECT_BLOCK_C(text, color) QSFMLP_BLOCK_C(text, color)
#define QSFMLP_OBJECT_NONSCOPED_BLOCK_C(text, color) QSFMLP_NONSCOPED_BLOCK_C(text, color)
#define QSFMLP_OBJECT_END_BLOCK QSFMLP_END_BLOCK;
#define QSFMLP_OBJECT_FUNCTION_C(color) QSFMLP_FUNCTION_C(color)
#define QSFMLP_OBJECT_BLOCK(text, colorStage) QSFMLP_BLOCK(text, CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE, colorStage))
#define QSFMLP_OBJECT_NONSCOPED_BLOCK(text, colorStage) QSFMLP_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE, colorStage))
#define QSFMLP_OBJECT_FUNCTION(colorStage) QSFMLP_FUNCTION(CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE, colorStage))
#define QSFMLP_OBJECT_VALUE(name, value) QSFMLP_VALUE(name, value)
#define QSFMLP_OBJECT_TEXT(name, value) QSFMLP_TEXT(name, value)

// Components
#define QSFMLP_COMPONENT_COLORBASE Yellow
#define QSFMLP_COMPONENT_BLOCK_C(text, color) QSFMLP_BLOCK_C(text, color)
#define QSFMLP_COMPONENT_NONSCOPED_BLOCK_C(text, color) QSFMLP_NONSCOPED_BLOCK_C(text, color)
#define QSFMLP_COMPONENT_END_BLOCK QSFMLP_END_BLOCK;
#define QSFMLP_COMPONENT_FUNCTION_C(color) QSFMLP_FUNCTION_C(color)
#define QSFMLP_COMPONENT_BLOCK(text, colorStage) QSFMLP_BLOCK(text, CONCAT_SYMBOLS(QSFMLP_COMPONENT_COLORBASE, colorStage))
#define QSFMLP_COMPONENT_NONSCOPED_BLOCK(text, colorStage) QSFMLP_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(QSFMLP_COMPONENT_COLORBASE, colorStage))
#define QSFMLP_COMPONENT_FUNCTION(colorStage) QSFMLP_FUNCTION(CONCAT_SYMBOLS(QSFMLP_COMPONENT_COLORBASE, colorStage))
#define QSFMLP_COMPONENT_VALUE(name, value) QSFMLP_VALUE(name, value)
#define QSFMLP_COMPONENT_TEXT(name, value) QSFMLP_TEXT(name, value)

// Physics
#define QSFMLP_PHYSICS_COLORBASE Blue
#define QSFMLP_PHYSICS_BLOCK_C(text, color) QSFMLP_BLOCK_C(text, color)
#define QSFMLP_PHYSICS_NONSCOPED_BLOCK_C(text, color) QSFMLP_NONSCOPED_BLOCK_C(text, color)
#define QSFMLP_PHYSICS_END_BLOCK QSFMLP_END_BLOCK;
#define QSFMLP_PHYSICS_FUNCTION_C(color) QSFMLP_FUNCTION_C(color)
#define QSFMLP_PHYSICS_BLOCK(text, colorStage) QSFMLP_BLOCK(text, CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE, colorStage))
#define QSFMLP_PHYSICS_NONSCOPED_BLOCK(text, colorStage) QSFMLP_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE, colorStage))
#define QSFMLP_PHYSICS_FUNCTION(colorStage) QSFMLP_FUNCTION(CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE, colorStage))
#define QSFMLP_PHYSICS_VALUE(name, value) QSFMLP_VALUE(name, value)
#define QSFMLP_PHYSICS_TEXT(name, value) QSFMLP_TEXT(name, value)

/*
// Colors for Canvas 
#define QSFMLP_CANVAS_COLORBASE Green
#define QSFMLP_CANVAS_COLOR_1  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_1 )
#define QSFMLP_CANVAS_COLOR_2  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_2 )
#define QSFMLP_CANVAS_COLOR_3  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_3 )
#define QSFMLP_CANVAS_COLOR_4  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_4 )
#define QSFMLP_CANVAS_COLOR_5  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_5 )
#define QSFMLP_CANVAS_COLOR_6  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_6 )
#define QSFMLP_CANVAS_COLOR_7  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_7 )
#define QSFMLP_CANVAS_COLOR_8  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_8 )
#define QSFMLP_CANVAS_COLOR_9  CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_9 )
#define QSFMLP_CANVAS_COLOR_10 CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_10)
#define QSFMLP_CANVAS_COLOR_11 CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_11) 
#define QSFMLP_CANVAS_COLOR_12 CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_12) 
#define QSFMLP_CANVAS_COLOR_13 CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_13) 
#define QSFMLP_CANVAS_COLOR_14 CONCAT_SYMBOLS(QSFMLP_CANVAS_COLORBASE , QSFMLP_COLOR_STAGE_14) 

// Colors for CanvasContainer
#define QSFMLP_CANVASCONTAINER_COLORBASE LightGreen
#define QSFMLP_CANVASCONTAINER_COLOR_1  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_1 )
#define QSFMLP_CANVASCONTAINER_COLOR_2  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_2 )
#define QSFMLP_CANVASCONTAINER_COLOR_3  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_3 )
#define QSFMLP_CANVASCONTAINER_COLOR_4  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_4 )
#define QSFMLP_CANVASCONTAINER_COLOR_5  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_5 )
#define QSFMLP_CANVASCONTAINER_COLOR_6  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_6 )
#define QSFMLP_CANVASCONTAINER_COLOR_7  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_7 )
#define QSFMLP_CANVASCONTAINER_COLOR_8  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_8 )
#define QSFMLP_CANVASCONTAINER_COLOR_9  CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_9 )
#define QSFMLP_CANVASCONTAINER_COLOR_10 CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_10)
#define QSFMLP_CANVASCONTAINER_COLOR_11 CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_11) 
#define QSFMLP_CANVASCONTAINER_COLOR_12 CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_12) 
#define QSFMLP_CANVASCONTAINER_COLOR_13 CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_13) 
#define QSFMLP_CANVASCONTAINER_COLOR_14 CONCAT_SYMBOLS(QSFMLP_CANVASCONTAINER_COLORBASE , QSFMLP_COLOR_STAGE_14) 

// Colors for Threads
#define QSFMLP_THREAD_COLORBASE Blue
#define QSFMLP_THREAD_COLOR_1  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_1 )
#define QSFMLP_THREAD_COLOR_2  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_2 )
#define QSFMLP_THREAD_COLOR_3  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_3 )
#define QSFMLP_THREAD_COLOR_4  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_4 )
#define QSFMLP_THREAD_COLOR_5  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_5 )
#define QSFMLP_THREAD_COLOR_6  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_6 )
#define QSFMLP_THREAD_COLOR_7  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_7 )
#define QSFMLP_THREAD_COLOR_8  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_8 )
#define QSFMLP_THREAD_COLOR_9  CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_9 )
#define QSFMLP_THREAD_COLOR_10 CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_10)
#define QSFMLP_THREAD_COLOR_11 CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_11) 
#define QSFMLP_THREAD_COLOR_12 CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_12) 
#define QSFMLP_THREAD_COLOR_13 CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_13) 
#define QSFMLP_THREAD_COLOR_14 CONCAT_SYMBOLS(QSFMLP_THREAD_COLORBASE , QSFMLP_COLOR_STAGE_14) 

// Colors for ObjectGroup
#define QSFMLP_OBJECTGROUP_COLORBASE Yellow
#define QSFMLP_OBJECTGROUP_COLOR_1  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_1 )
#define QSFMLP_OBJECTGROUP_COLOR_2  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_2 )
#define QSFMLP_OBJECTGROUP_COLOR_3  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_3 )
#define QSFMLP_OBJECTGROUP_COLOR_4  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_4 )
#define QSFMLP_OBJECTGROUP_COLOR_5  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_5 )
#define QSFMLP_OBJECTGROUP_COLOR_6  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_6 )
#define QSFMLP_OBJECTGROUP_COLOR_7  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_7 )
#define QSFMLP_OBJECTGROUP_COLOR_8  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_8 )
#define QSFMLP_OBJECTGROUP_COLOR_9  CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_9 )
#define QSFMLP_OBJECTGROUP_COLOR_10 CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_10)
#define QSFMLP_OBJECTGROUP_COLOR_11 CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_11) 
#define QSFMLP_OBJECTGROUP_COLOR_12 CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_12) 
#define QSFMLP_OBJECTGROUP_COLOR_13 CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_13) 
#define QSFMLP_OBJECTGROUP_COLOR_14 CONCAT_SYMBOLS(QSFMLP_OBJECTGROUP_COLORBASE , QSFMLP_COLOR_STAGE_14) 


// Colors for CanvasObject 
#define QSFMLP_OBJECT_COLORBASE Orange
#define QSFMLP_OBJECT_COLOR_1  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_1 )
#define QSFMLP_OBJECT_COLOR_2  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_2 )
#define QSFMLP_OBJECT_COLOR_3  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_3 )
#define QSFMLP_OBJECT_COLOR_4  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_4 )
#define QSFMLP_OBJECT_COLOR_5  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_5 )
#define QSFMLP_OBJECT_COLOR_6  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_6 )
#define QSFMLP_OBJECT_COLOR_7  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_7 )
#define QSFMLP_OBJECT_COLOR_8  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_8 )
#define QSFMLP_OBJECT_COLOR_9  CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_9 )
#define QSFMLP_OBJECT_COLOR_10 CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_10)
#define QSFMLP_OBJECT_COLOR_11 CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_11) 
#define QSFMLP_OBJECT_COLOR_12 CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_12) 
#define QSFMLP_OBJECT_COLOR_13 CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_13) 
#define QSFMLP_OBJECT_COLOR_14 CONCAT_SYMBOLS(QSFMLP_OBJECT_COLORBASE , QSFMLP_COLOR_STAGE_14) 

// Colors for Physics stuff 
#define QSFMLP_PHYSICS_COLORBASE Cyan
#define QSFMLP_PHYSICS_COLOR_1  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_1 )
#define QSFMLP_PHYSICS_COLOR_2  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_2 )
#define QSFMLP_PHYSICS_COLOR_3  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_3 )
#define QSFMLP_PHYSICS_COLOR_4  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_4 )
#define QSFMLP_PHYSICS_COLOR_5  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_5 )
#define QSFMLP_PHYSICS_COLOR_6  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_6 )
#define QSFMLP_PHYSICS_COLOR_7  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_7 )
#define QSFMLP_PHYSICS_COLOR_8  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_8 )
#define QSFMLP_PHYSICS_COLOR_9  CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_9 )
#define QSFMLP_PHYSICS_COLOR_10 CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_10)
#define QSFMLP_PHYSICS_COLOR_11 CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_11) 
#define QSFMLP_PHYSICS_COLOR_12 CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_12) 
#define QSFMLP_PHYSICS_COLOR_13 CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_13) 
#define QSFMLP_PHYSICS_COLOR_14 CONCAT_SYMBOLS(QSFMLP_PHYSICS_COLORBASE , QSFMLP_COLOR_STAGE_14) 
*/